// <auto-generated />
using System;
using DbWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbWebApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113130052_Teacher1")]
    partial class Teacher1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbWebApplication.Models.AppUserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("QrCodeToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherModelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TokenDateExpired")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherModelId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            FatherName = "Admin",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "$2a$11$A7U9aI.Fw3LTLNwUWN7YMupmio/QLURgwq0j73Pz3YjRTXLIDorWi",
                            Role = 2
                        });
                });

            modelBuilder.Entity("DbWebApplication.Models.FacultyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("DbWebApplication.Models.LabModel", b =>
                {
                    b.Property<int>("LabWorkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabWorkID"));

                    b.Property<string>("LabWorkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("LabWorkID");

                    b.HasIndex("SubjectID");

                    b.ToTable("LabWorks");
                });

            modelBuilder.Entity("DbWebApplication.Models.LabWorkGradeModel", b =>
                {
                    b.Property<int>("LabWorkGradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabWorkGradeID"));

                    b.Property<int>("GradeValue")
                        .HasColumnType("int");

                    b.Property<int>("LabWorkID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("LabWorkGradeID");

                    b.HasIndex("LabWorkID");

                    b.HasIndex("StudentID");

                    b.ToTable("LabWorkGrade");
                });

            modelBuilder.Entity("DbWebApplication.Models.Pair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleDayId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleDayId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Pair");
                });

            modelBuilder.Entity("DbWebApplication.Models.ScheduleDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyScheduleForWeekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyScheduleForWeekId");

                    b.ToTable("ScheduleDay");
                });

            modelBuilder.Entity("DbWebApplication.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DbWebApplication.Models.SessionGrades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SessionSubjectsId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionSubjectsId");

                    b.HasIndex("StudentId");

                    b.ToTable("SessionGrades");
                });

            modelBuilder.Entity("DbWebApplication.Models.SessionSubjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SessionSubjects");
                });

            modelBuilder.Entity("DbWebApplication.Models.SpecialtyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("DbWebApplication.Models.SpecialtyScheduleForWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartOfWeek")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("SpecialtyScheduleForWeeks");
                });

            modelBuilder.Entity("DbWebApplication.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DbWebApplication.Models.StudyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("DbWebApplication.Models.SubjectGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("StudyPlanId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectModelSubjectID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudyPlanId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectModelSubjectID");

                    b.ToTable("SubjectsGrades");
                });

            modelBuilder.Entity("DbWebApplication.Models.SubjectModel", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("GradeECTS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeNational")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("SubjectID");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("DbWebApplication.Models.TeacherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("StudyPlanSubjectModel", b =>
                {
                    b.Property<int>("StudyPlansId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectsSubjectID")
                        .HasColumnType("int");

                    b.HasKey("StudyPlansId", "SubjectsSubjectID");

                    b.HasIndex("SubjectsSubjectID");

                    b.ToTable("StudyPlanSubjectModel");
                });

            modelBuilder.Entity("DbWebApplication.Models.AppUserModel", b =>
                {
                    b.HasOne("DbWebApplication.Models.TeacherModel", "TeacherModel")
                        .WithMany()
                        .HasForeignKey("TeacherModelId");

                    b.Navigation("TeacherModel");
                });

            modelBuilder.Entity("DbWebApplication.Models.LabModel", b =>
                {
                    b.HasOne("DbWebApplication.Models.SubjectModel", "Subject")
                        .WithMany("LabWorks")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DbWebApplication.Models.LabWorkGradeModel", b =>
                {
                    b.HasOne("DbWebApplication.Models.LabModel", "LabWork")
                        .WithMany("LabWorkGrades")
                        .HasForeignKey("LabWorkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbWebApplication.Models.StudentModel", "Student")
                        .WithMany("LabWorkGrades")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabWork");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DbWebApplication.Models.Pair", b =>
                {
                    b.HasOne("DbWebApplication.Models.ScheduleDay", "ScheduleDay")
                        .WithMany("Pairs")
                        .HasForeignKey("ScheduleDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbWebApplication.Models.SubjectModel", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleDay");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DbWebApplication.Models.ScheduleDay", b =>
                {
                    b.HasOne("DbWebApplication.Models.SpecialtyScheduleForWeek", "SpecialtyScheduleForWeek")
                        .WithMany("Days")
                        .HasForeignKey("SpecialtyScheduleForWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecialtyScheduleForWeek");
                });

            modelBuilder.Entity("DbWebApplication.Models.Session", b =>
                {
                    b.HasOne("DbWebApplication.Models.SpecialtyModel", "Specialty")
                        .WithMany("Sessions")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("DbWebApplication.Models.SessionGrades", b =>
                {
                    b.HasOne("DbWebApplication.Models.SessionSubjects", "SessionSubject")
                        .WithMany("SessionGrades")
                        .HasForeignKey("SessionSubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbWebApplication.Models.StudentModel", "Student")
                        .WithMany("SessionGrades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionSubject");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DbWebApplication.Models.SessionSubjects", b =>
                {
                    b.HasOne("DbWebApplication.Models.Session", "Session")
                        .WithMany("SessionSubjects")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbWebApplication.Models.TeacherModel", "Teacher")
                        .WithMany("SessionSubjects")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Session");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DbWebApplication.Models.SpecialtyModel", b =>
                {
                    b.HasOne("DbWebApplication.Models.FacultyModel", "Faculty")
                        .WithMany("Specialties")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("DbWebApplication.Models.SpecialtyScheduleForWeek", b =>
                {
                    b.HasOne("DbWebApplication.Models.SpecialtyModel", "Specialty")
                        .WithMany("SpecialtyScheduleForWeeks")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("DbWebApplication.Models.StudentModel", b =>
                {
                    b.HasOne("DbWebApplication.Models.AppUserModel", "AppUser")
                        .WithOne("Student")
                        .HasForeignKey("DbWebApplication.Models.StudentModel", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbWebApplication.Models.SpecialtyModel", "Specialty")
                        .WithMany("Students")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("DbWebApplication.Models.StudyPlan", b =>
                {
                    b.HasOne("DbWebApplication.Models.SpecialtyModel", "Specialty")
                        .WithMany("StudyPlans")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("DbWebApplication.Models.SubjectGrade", b =>
                {
                    b.HasOne("DbWebApplication.Models.StudentModel", "Student")
                        .WithMany("SubjectGrades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbWebApplication.Models.StudyPlan", "StudyPlan")
                        .WithMany()
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbWebApplication.Models.SubjectModel", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbWebApplication.Models.SubjectModel", null)
                        .WithMany("SubjectGrades")
                        .HasForeignKey("SubjectModelSubjectID");

                    b.Navigation("Student");

                    b.Navigation("StudyPlan");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DbWebApplication.Models.SubjectModel", b =>
                {
                    b.HasOne("DbWebApplication.Models.TeacherModel", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DbWebApplication.Models.TeacherModel", b =>
                {
                    b.HasOne("DbWebApplication.Models.FacultyModel", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudyPlanSubjectModel", b =>
                {
                    b.HasOne("DbWebApplication.Models.StudyPlan", null)
                        .WithMany()
                        .HasForeignKey("StudyPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbWebApplication.Models.SubjectModel", null)
                        .WithMany()
                        .HasForeignKey("SubjectsSubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbWebApplication.Models.AppUserModel", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("DbWebApplication.Models.FacultyModel", b =>
                {
                    b.Navigation("Specialties");
                });

            modelBuilder.Entity("DbWebApplication.Models.LabModel", b =>
                {
                    b.Navigation("LabWorkGrades");
                });

            modelBuilder.Entity("DbWebApplication.Models.ScheduleDay", b =>
                {
                    b.Navigation("Pairs");
                });

            modelBuilder.Entity("DbWebApplication.Models.Session", b =>
                {
                    b.Navigation("SessionSubjects");
                });

            modelBuilder.Entity("DbWebApplication.Models.SessionSubjects", b =>
                {
                    b.Navigation("SessionGrades");
                });

            modelBuilder.Entity("DbWebApplication.Models.SpecialtyModel", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("SpecialtyScheduleForWeeks");

                    b.Navigation("Students");

                    b.Navigation("StudyPlans");
                });

            modelBuilder.Entity("DbWebApplication.Models.SpecialtyScheduleForWeek", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("DbWebApplication.Models.StudentModel", b =>
                {
                    b.Navigation("LabWorkGrades");

                    b.Navigation("SessionGrades");

                    b.Navigation("SubjectGrades");
                });

            modelBuilder.Entity("DbWebApplication.Models.SubjectModel", b =>
                {
                    b.Navigation("LabWorks");

                    b.Navigation("SubjectGrades");
                });

            modelBuilder.Entity("DbWebApplication.Models.TeacherModel", b =>
                {
                    b.Navigation("SessionSubjects");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
