<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Identity" Version="1.13.1" />
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.3" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.3" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
      <PackageReference Include="Microsoft.Identity.Client" Version="4.66.1" />
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.3" />
      <PackageReference Include="ZXing.Net" Version="0.16.9" />
      <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.12" />
    </ItemGroup>

    <ItemGroup>
      <None Include="wwwroot\css\reset.css" />
      <None Include="wwwroot\css\style.css" />
      <None Include="wwwroot\fonts\Jaldi-Bold.woff2" />
      <None Include="wwwroot\fonts\Jaldi-Regular.woff2" />
      <None Include="wwwroot\icons\storage-svgrepo-com.svg" />
      <None Include="wwwroot\images\inet.svg" />
      <None Include="wwwroot\images\iueh-logo-gerb.png" />
      <None Include="wwwroot\images\Logo__megu.png" />
      <None Include="wwwroot\images\Logo__megu__footer.png" />
      <None Include="wwwroot\images\photo_2024-12-09_16-08-37.jpg" />
      <None Include="wwwroot\images\ps_5.svg" />
      <None Include="wwwroot\images\Rating.svg" />
      <None Include="wwwroot\images\Англійська.svg" />
      <None Include="wwwroot\images\Бази даних.svg" />
      <None Include="wwwroot\images\Безпека програм.svg" />
      <None Include="wwwroot\images\Групова динаміка.svg" />
      <None Include="wwwroot\images\Пайтон.svg" />
      <None Include="wwwroot\images\Філософія_1.svg" />
      <None Include="wwwroot\js\main.js" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\AccessDenied.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ConfirmEmail.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ExternalLogin.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ForgotPassword.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Lockout.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Login.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\LoginWith2fa.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\LoginWithRecoveryCode.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Logout.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\ChangePassword.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\DeletePersonalData.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\Disable2fa.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\DownloadPersonalData.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\Email.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\EnableAuthenticator.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\ExternalLogins.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\GenerateRecoveryCodes.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\PersonalData.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\ResetAuthenticator.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\SetPassword.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\ShowRecoveryCodes.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\TwoFactorAuthentication.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\_ManageNav.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\_StatusMessage.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Register.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\RegisterConfirmation.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ResendEmailConfirmation.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ResetPassword.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\_StatusMessage.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Error.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\_ValidationScriptsPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\_ViewStart.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Student\GradesOfStudent.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Student\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Student\StudentZalikovka.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Student\SubjectDetails.cshtml" />
      <_ContentIncludedByDefault Remove="Views\User\Login.cshtml" />
      <_ContentIncludedByDefault Remove="Views\User\LoginWithQrCode.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Login.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ValidationScriptsPartial.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ViewStart.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ui__pages-main\css\" />
      <Folder Include="ui__pages-main\js\" />
    </ItemGroup>

</Project>
